import { db } from "hatchable";

export const MONEY_SCALE = 2;
export const CONSUMPTION_SCALE = 3;

export function fail(code, message, status = 400) {
  const e = new Error(message); e.code = code; e.httpStatus = status; return e;
}

export function isUuid(v) { return typeof v === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v); }
export function validDate(v) { return typeof v === "string" && /^\d{4}-\d{2}-\d{2}$/.test(v) && !Number.isNaN(Date.parse(v + "T00:00:00Z")); }
export function daysInMonth(year, month) { return new Date(Date.UTC(year, month, 0)).getUTCDate(); }
export function addDays(date, n) { const d=new Date(date+"T00:00:00Z"); d.setUTCDate(d.getUTCDate()+n); return d.toISOString().slice(0,10); }
export function maxDate(a,b){return a>b?a:b} export function minDate(a,b){return a<b?a:b}
function scaled(value, scale) { const s=String(value??"0").trim(); if(!/^\d+(?:\.\d+)?$/.test(s)) throw fail("VALIDATION_ERROR",`Invalid decimal value: ${s}`); const [whole,frac=""]=s.split("."); if(frac.length>scale) throw fail("VALIDATION_ERROR",`Too many decimal places: ${s}`); return BigInt(whole)*(10n**BigInt(scale))+BigInt((frac+"0".repeat(scale)).slice(0,scale)||"0"); }
export function decimal(value, scale=2) { const x=scaled(value,scale),base=10n**BigInt(scale); return `${x/base}.${(x%base).toString().padStart(scale,"0")}`; }
export function fromScaledInt(x,scale=2){const n=BigInt(x),base=10n**BigInt(scale);return `${n/base}.${(n%base).toString().padStart(scale,"0")}`}
export function compareDecimal(a,b,scale=3){const x=scaled(a,scale),y=scaled(b,scale);return x<y?-1:x>y?1:0}
export function addMoney(a,b){return decimal((scaled(a,2)+scaled(b,2)).toString().replace(/(\d{2})$/,'.$1'),2)}
export function moneyFromMinor(minor){const x=BigInt(minor),base=100n;return `${x/base}.${(x%base).toString().padStart(2,"0")}`}
export function moneyMinor(value){return scaled(value,2)}
export function multiplyToMoney(quantity,quantityScale,rate,rateScale){const q=scaled(quantity,quantityScale),r=scaled(rate,rateScale),raw=q*r,divisor=10n**BigInt(quantityScale+rateScale-2),rounded=(raw+divisor/2n)/divisor;return moneyFromMinor(rounded)}
export function sumMoney(values){let total=0n;for(const v of values)total+=moneyMinor(v);return moneyFromMinor(total)}
export function calculateConsumption(previous,current){if(previous===null||previous===undefined)return{consumption:null,firstReading:true};if(compareDecimal(current,previous,CONSUMPTION_SCALE)<0)throw fail("INVALID_METER_READING","Current meter reading cannot be lower than the previous reading");const diff=scaled(current,CONSUMPTION_SCALE)-scaled(previous,CONSUMPTION_SCALE);return{consumption:fromScaledInt(diff,CONSUMPTION_SCALE),firstReading:false}}
export function calculateSlab(consumption,slabs){const c=scaled(consumption,CONSUMPTION_SCALE),ordered=[...slabs].sort((a,b)=>Number(a.min_units)-Number(b.min_units));let previousEnd=0n,minor=0n,fixed=0n;for(const s of ordered){const min=scaled(s.min_units,CONSUMPTION_SCALE),max=s.max_units==null?null:scaled(s.max_units,CONSUMPTION_SCALE);if(min<previousEnd)throw fail("INVALID_SLABS","Utility slabs overlap");previousEnd=max??c;if(c<=min)continue;const end=max===null?c:(c<max?c:max);if(end>min){const units=end-min,rate=scaled(s.rate_per_unit,4),divisor=10n**BigInt(CONSUMPTION_SCALE+4-2);minor+=(units*rate+divisor/2n)/divisor;fixed+=scaled(s.fixed_charge||0,2)}if(max!==null&&c<=max)break}return{amount:moneyFromMinor(minor+fixed),fixed_charge:moneyFromMinor(fixed)}}
async function getLease(leaseId){const {rows}=await db.query(`SELECT l.*,u.unit_number,u.property_id,p.name property_name,t.name tenant_name FROM leases l JOIN units u ON u.id=l.unit_id JOIN properties p ON p.id=u.property_id JOIN tenants t ON t.id=l.tenant_id WHERE l.id=$1`,[leaseId]);if(!rows[0])throw fail("LEASE_NOT_FOUND","Lease not found",404);return rows[0]}
async function rentForPeriod(lease,start,end){const {rows}=await db.query(`SELECT id,effective_from,effective_to,monthly_rent,reason FROM rent_history WHERE lease_id=$1 AND effective_from <= $2 AND (effective_to IS NULL OR effective_to >= $3) ORDER BY effective_from DESC LIMIT 1`,[lease.id,start,end]);if(rows[0])return rows[0];return{id:null,effective_from:lease.start_date,effective_to:lease.end_date,monthly_rent:lease.monthly_rent,reason:"Lease base rent fallback"}}
async function utilityConfig(unitId,propertyId,type,start,end){const {rows}=await db.query(`SELECT * FROM utility_configs WHERE utility_type=$1 AND effective_from <= $2 AND (effective_to IS NULL OR effective_to >= $3) AND unit_id=$4 ORDER BY effective_from DESC LIMIT 1`,[type,start,end,unitId]);if(rows[0])return{...rows[0],scope:"unit"};const {rows:propertyRows}=await db.query(`SELECT * FROM utility_configs WHERE utility_type=$1 AND effective_from <= $2 AND (effective_to IS NULL OR effective_to >= $3) AND property_id=$4 ORDER BY effective_from DESC LIMIT 1`,[type,start,end,propertyId]);if(propertyRows[0])return{...propertyRows[0],scope:"property"};return null}
async function utilityRate(config,start,end){const {rows}=await db.query(`SELECT * FROM utility_rates WHERE utility_config_id=$1 AND effective_from <= $2 AND (effective_to IS NULL OR effective_to >= $3) ORDER BY effective_from DESC LIMIT 1`,[config.id,start,end]);return rows[0]||null}
async function utilitySlabs(configId){const {rows}=await db.query(`SELECT * FROM utility_slabs WHERE utility_config_id=$1 ORDER BY min_units ASC`,[configId]);return rows}
async function meterFor(unitId,type){const {rows}=await db.query(`SELECT * FROM meters WHERE unit_id=$1 AND utility_type=$2 AND status='active' LIMIT 1`,[unitId,type]);return rows[0]||null}
async function readingsFor(meter,end){const {rows}=await db.query(`SELECT id,reading_date,reading_value,reading_source FROM meter_readings WHERE meter_id=$1 AND reading_date <= $2 ORDER BY reading_date DESC LIMIT 2`,[meter.id,end]);if(!rows[0])throw fail("METER_READING_REQUIRED",`${meter.utility_type} billing cannot be calculated because the current meter reading is missing for the billing period ending ${end}`);if(!rows[1])throw fail("METER_READING_REQUIRED",`${meter.utility_type} billing cannot be calculated because the previous meter reading is missing before ${rows[0].reading_date}`);return{current:rows[0],previous:rows[1]}}
async function calculateUtility(unitId,propertyId,type,start,end){const config=await utilityConfig(unitId,propertyId,type,start,end);if(!config)return{utility:type,configured:false,amount:"0.00",warnings:[`${type} has no billing configuration`],errors:[]};if(config.billing_method==='included_in_rent')return{utility:type,configured:true,scope:config.scope,billing_method:config.billing_method,amount:"0.00",included_in_rent:true,warnings:[],errors:[]};const rate=await utilityRate(config,start,end),slabs=await utilitySlabs(config.id);if(["per_unit","per_unit_fixed","slab"].includes(config.billing_method)&&config.billing_method!=='slab'&&!rate?.rate_per_unit)throw fail("UTILITY_RATE_REQUIRED",`${type} per-unit rate is missing`);if(config.billing_method==='slab'&&!slabs.length)throw fail("UTILITY_SLAB_REQUIRED",`${type} slab configuration is missing`);let meter=null,readings=null,consumption=null,amount="0.00";if(config.billing_method!=='fixed'){meter=await meterFor(unitId,type);if(!meter)throw fail("METER_REQUIRED",`${type} billing is metered but no active meter is configured for this unit`);readings=await readingsFor(meter,end);const c=calculateConsumption(readings.previous.reading_value,readings.current.reading_value);consumption=c.consumption;if(c.firstReading)throw fail("METER_READING_REQUIRED",`${type} billing requires a previous reading before ${readings.current.reading_date}`)}if(config.billing_method==='fixed')amount=decimal(config.fixed_amount,2);else if(config.billing_method==='per_unit')amount=multiplyToMoney(consumption,3,rate.rate_per_unit,4);else if(config.billing_method==='per_unit_fixed')amount=addMoney(multiplyToMoney(consumption,3,rate.rate_per_unit,4),decimal(rate.fixed_charge||config.fixed_amount||0,2));else if(config.billing_method==='slab')amount=calculateSlab(consumption,slabs).amount;return{utility:type,configured:true,scope:config.scope,config_id:config.id,billing_method:config.billing_method,rate_id:rate?.id||null,rate_per_unit:rate?.rate_per_unit||null,fixed_charge:rate?.fixed_charge||config.fixed_amount||"0.00",meter_id:meter?.id||null,meter_number:meter?.meter_number||null,previous_reading:readings?.previous?.reading_value??null,current_reading:readings?.current?.reading_value??null,previous_reading_date:readings?.previous?.reading_date??null,current_reading_date:readings?.current?.reading_date??null,consumption,amount,included_in_rent:false,warnings:[],errors:[]}}
export async function buildPreview(input){const{lease_id,billing_period_start:start,billing_period_end:end}=input||{};if(!isUuid(lease_id)||!validDate(start)||!validDate(end)||start>end)throw fail("VALIDATION_ERROR","lease_id, billing_period_start and billing_period_end are required and must form a valid date range");const lease=await getLease(lease_id);if(lease.start_date>end||(lease.end_date&&lease.end_date<start)||['terminated','expired'].includes(lease.status)&&lease.end_date&&lease.end_date<start)throw fail("LEASE_NOT_ACTIVE","Lease is not valid for the requested billing period");const rent=await rentForPeriod(lease,start,end);const periodDays=Math.round((Date.parse(end)-Date.parse(start))/86400000)+1;let rentAmount=decimal(rent.monthly_rent,2),proration={strategy:lease.billing_proration_strategy||'full_month',factor:"1.000",occupied_days:periodDays,period_days:periodDays};if((lease.billing_proration_strategy||'full_month')==='prorated_actual_days'){const occupiedStart=maxDate(start,lease.start_date),occupiedEnd=minDate(end,lease.end_date||end),occupiedDays=occupiedStart>occupiedEnd?0:Math.round((Date.parse(occupiedEnd)-Date.parse(occupiedStart))/86400000)+1,y=Number(start.slice(0,4)),m=Number(start.slice(5,7)),monthDays=daysInMonth(y,m),minor=moneyMinor(rent.monthly_rent),prorated=(minor*BigInt(occupiedDays)+BigInt(monthDays/2))/BigInt(monthDays);rentAmount=moneyFromMinor(prorated);proration={strategy:'prorated_actual_days',factor:`${occupiedDays}/${monthDays}`,occupied_days:occupiedDays,period_days:monthDays}}const electricity=await calculateUtility(lease.unit_id,lease.property_id,'electricity',start,end),water=await calculateUtility(lease.unit_id,lease.property_id,'water',start,end);const items=[{type:'rent',description:`Rent - ${start.slice(0,7)}`,quantity:"1",unit_rate:rentAmount,amount:rentAmount,metadata:{rent_history_id:rent.id,monthly_rent:rent.monthly_rent,proration}}];for(const u of[electricity,water])if(u.amount!=="0.00")items.push({type:u.utility,description:`${u.utility[0].toUpperCase()+u.utility.slice(1)} charge - ${start.slice(0,7)}`,quantity:u.consumption||"1",unit_rate:u.rate_per_unit||u.amount,amount:u.amount,metadata:u});const subtotal=sumMoney(items.map(x=>x.amount));const dueDate=new Date(start+"T00:00:00Z"),dueDay=Math.min(Number(lease.rent_due_day),daysInMonth(dueDate.getUTCFullYear(),dueDate.getUTCMonth()+1));dueDate.setUTCDate(dueDay);const due=dueDate.toISOString().slice(0,10);return{lease,billing_period_start:start,billing_period_end:end,billing_period:start.slice(0,7),due_date:due,rent,proration,utilities:{electricity,water},items,subtotal,adjustments:"0.00",total:subtotal,warnings:[...electricity.warnings,...water.warnings],errors:[...electricity.errors,...water.errors]}}
export async function invoiceDetails(id){const{rows}=await db.query(`SELECT i.*,l.tenant_id,l.unit_id,t.name tenant_name,u.unit_number,p.name property_name FROM invoices i JOIN leases l ON l.id=i.lease_id JOIN tenants t ON t.id=l.tenant_id JOIN units u ON u.id=l.unit_id JOIN properties p ON p.id=u.property_id WHERE i.id=$1`,[id]);if(!rows[0])throw fail("NOT_FOUND","Invoice not found",404);const invoice=rows[0],{rows:items}=await db.query(`SELECT * FROM invoice_items WHERE invoice_id=$1 ORDER BY created_at`,[id]),{rows:payments}=await db.query(`SELECT * FROM payments WHERE invoice_id=$1 ORDER BY payment_date,created_at`,[id]);return{...invoice,items,payments}}
export async function balance(id){const invoice=await invoiceDetails(id),paid=invoice.payments.reduce((a,p)=>a+moneyMinor(p.amount),0n),total=moneyMinor(invoice.total),due=total-paid,amountDue=due>0n?due:0n,status=amountDue===0n?'paid':paid>0n?'partially_paid':(new Date().toISOString().slice(0,10)>invoice.due_date?'overdue':'issued');return{total:moneyFromMinor(total),amount_paid:moneyFromMinor(paid),amount_due:moneyFromMinor(amountDue),status}}